### PR TITLE
improve integration with upstream csmock

### PR DESCRIPTION
**Pull request by kdudka**
... based on the following upstream pull requests:
https://github.com/kdudka/csmock/pull/30 - csmock: do not hard-wire ordering of plug-ins
https://github.com/kdudka/csmock/pull/31 - csmock: handle props.add_repos in try_install()

### CODE REVIEW

**Comment by kdudka** [comment]
This can be installed on a testing system with Fedora 34 using the following steps:
```
sudo yum install @buildsys-build
sudo yum builddep csmock
git clone https://github.com/aufover/csmock.git
cd csmock
./make-srpm.sh
mkdir inst
rpmbuild --define "_rpmdir $PWD" --rebuild ./*.src.rpm
sudo yum install noarch/*.rpm
```

**Comment by kdudka** [comment]
I did not mean to close this.  It was just an unintentional side-effect of deleting the master branch.

**Comment by psimovec** [comment]
@kdudka I needed one more dependency yum-utils on a clean machine
sudo yum install @buildsys-build yum-utils

**Comment by kdudka** [comment]
@psimovec What exactly happened when `yum-utils` was not installed?  I am not able to reproduce it...

**Comment by kdudka** [comment]
Got it. We need to install `dnf-plugins-core`  for `yum builddep` to work.  Comment updated.  Thanks!

**Pull request closed without merging**
